# Generated by Django 3.1.7 on 2021-09-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
