# Generated by Django 3.1.7 on 2021-09-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0002_auto_20210927_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recieved_date',
            new_name='received_date',
        ),
    ]
